// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0hT7D_OlU1dYQENuJQhBrgOwUTbckt30',
    appId: '1:784337838266:web:9321c48e653dc03124a283',
    messagingSenderId: '784337838266',
    projectId: 'm-lovers-c94ff',
    authDomain: 'm-lovers-c94ff.firebaseapp.com',
    storageBucket: 'm-lovers-c94ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwnkTzG1SmoVq7oO3XEsKWvcHCO9dKCvs',
    appId: '1:784337838266:android:2616e945f3d8a47d24a283',
    messagingSenderId: '784337838266',
    projectId: 'm-lovers-c94ff',
    storageBucket: 'm-lovers-c94ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmd_V_FtN9Bh0WEBA2g1wlepebPUzr8ko',
    appId: '1:784337838266:ios:9d93c1931300e7eb24a283',
    messagingSenderId: '784337838266',
    projectId: 'm-lovers-c94ff',
    storageBucket: 'm-lovers-c94ff.appspot.com',
    iosBundleId: 'com.example.dattingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmd_V_FtN9Bh0WEBA2g1wlepebPUzr8ko',
    appId: '1:784337838266:ios:9d93c1931300e7eb24a283',
    messagingSenderId: '784337838266',
    projectId: 'm-lovers-c94ff',
    storageBucket: 'm-lovers-c94ff.appspot.com',
    iosBundleId: 'com.example.dattingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0hT7D_OlU1dYQENuJQhBrgOwUTbckt30',
    appId: '1:784337838266:web:a2df7728b3cc70d224a283',
    messagingSenderId: '784337838266',
    projectId: 'm-lovers-c94ff',
    authDomain: 'm-lovers-c94ff.firebaseapp.com',
    storageBucket: 'm-lovers-c94ff.appspot.com',
  );

}